name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout кода
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Шаг 2: Логин в DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Сборка Docker-образа
      - name: Build the Docker image
        run: |
          docker build -t your-dockerhub-username/your-service-name:latest .
          docker build -t your-dockerhub-username/your-service-name:${{ github.sha }} .

      # Шаг 4: Публикация образа в DockerHub
      - name: Push the Docker image
        run: |
          docker push your-dockerhub-username/your-service-name:latest
          docker push your-dockerhub-username/your-service-name:${{ github.sha }}
